services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: cars
      POSTGRES_PASSWORD: cars
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: